### ISSUE TITLE
vagrant up fail

### ISSUE THREAD

**Issue by tienya** [ghtorrent/ghtorrent-vagrant#1]
> Failed to mount folders in Linux guest. This is usually because
> the "vboxsf" file system is not available. Please verify that
> the guest additions are properly installed in the guest and
> can work properly. The command attempted was:
> 
> mount -t vboxsf -o uid=`id -u root`,gid=`getent group vagrant | cut -d: -f3` tmp_vagrant-puppet_modules-53e02185df0ffd3424f87ed4f1556d19 /tmp/vagrant-puppet/modules-53e02185df0ffd3424f87ed4f1556d19
> mount -t vboxsf -o uid=`id -u root`,gid=`id -g vagrant` tmp_vagrant-puppet_modules-53e02185df0ffd3424f87ed4f1556d19 /tmp/vagrant-puppet/modules-53e02185df0ffd3424f87ed4f1556d19
> 
> The error output from the last command was:
> 
> stdin: is not a tty
> mount: unknown filesystem type 'vboxsf'

Mac 10.11.3
Vagrant 1.8.1
Virtualbox 5.0.10 r104061

**Comment by gousiosg** [comment]
This looks like a Vagrant/VirtualBox incompatibility. My setup works perfectly with the following versions:

Mac 10.11.3
Vagrant 1.7.4
VBox Version 5.0.6 r103037

**Comment by tienya** [comment]
close
