### ISSUE TITLE
issues running ghtorrent vagrant

### ISSUE THREAD

**Issue by letimome** [ghtorrent/ghtorrent-vagrant#6]
Hi there!!

I am trying to run ghtorrent in my local computer (Mac OS X). When executing `ght-retrieve-repo -c ./config.yaml ownerName repoName `, I get the following error:

```
Overriding configuration mirror_history_pages_back=1 with new value 1000
Mysql2::Error: Access denied for user 'ghtorrent'@'localhost' (using password: YES)
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect'
```

To resolve this issue I needed to install mongodb and mysql (creating also ghtorrent) in my local computer and so on. Although I am getting now this error: 
```
Overriding configuration mirror_history_pages_back=1 with new value 1000
WARN, 2017-04-03T11:37:02+02:00, ght -- ghtorrent.rb: Transaction failed (11 ms)
Mysql2::Error: Unknown column 'fake' in 'field list'
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
```

Any ideas what is wrong? How can I connect to vagrant's MySQL/mongodb instead to my local ones? 
Thanks!

**Comment by gousiosg** [comment]
Hi can you be a bit more specific about the problems you are facing? I 've rerun the provisioning process and works as expected...

**Comment by letimome** [comment]
Sorry to "waste" your time. I feel stupid now... 
I was executing the command outside vagrant, in my terminal command prompt. So I have just cloned this repo when inside the virtual machine, and then run `vagrant@jessie:~/ghtorrent-vagrant$ ght-retrieve-repo -c config.yaml letimome VODPlayer-CoreAssets-CI`
Works perfect. Thanks, and sorry
